### ISSUE TITLE
javadoc Ensure that dot is in your path and that its path does not contain spaces

### ISSUE THREAD

**Issue by hlzhang** [ci-and-cd/maven-build#7]
java.io.IOException: Cannot run program "dot": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at org.umlgraph.doclet.UmlGraphDoc.runGraphviz(UmlGraphDoc.java:144)
	at org.umlgraph.doclet.UmlGraphDoc.generateContextDiagrams(UmlGraphDoc.java:126)
	at org.umlgraph.doclet.UmlGraphDoc.start(UmlGraphDoc.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
	at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
	at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
	at com.sun.tools.javadoc.Start.begin(Start.java:219)
	at com.sun.tools.javadoc.Start.begin(Start.java:205)
	at com.sun.tools.javadoc.Main.execute(Main.java:64)
	at com.sun.tools.javadoc.Main.main(Main.java:54)

**Comment by hlzhang** [comment]
install graphviz
